# Summarize simulated statistics across multiple networks
rm(list=ls())

# Libraries ----------
library(network)
library(ergm)
library(ergm.userterms)

# Data ----------
load("/home/bryan/Desktop/HepCep_Project_ND/Old_Organization/hepcep_networks/fit-ergms/out/sims-racemix-plus-dist-plus-negbin-indeg0-1-outdeg0-3.RData")
nsim.vec = 1:100
# Compute summaries and IQRs ----------
paste("outdegrees")
#quantiles
mean(outdeg0)
quantile(outdeg0, probs = c(2.5/100, 97.5/100))
mean(outdeg1)
quantile(outdeg1, probs = c(2.5/100, 97.5/100))
mean(outdeg2)
quantile(outdeg2, probs = c(2.5/100, 97.5/100))
mean(outdeg3)
quantile(outdeg3, probs = c(2.5/100, 97.5/100))
mean(outdeg4)
quantile(outdeg4, probs = c(2.5/100, 97.5/100))

paste("indegrees:")
#quantiles
mean(indeg0)
quantile(indeg0, probs = c(2.5/100, 97.5/100))
mean(indeg1)
quantile(indeg1, probs = c(2.5/100, 97.5/100))
mean(indeg2)
quantile(indeg2, probs = c(2.5/100, 97.5/100))
mean(indeg3)
quantile(indeg3, probs = c(2.5/100, 97.5/100))
mean(indeg4)
quantile(indeg4, probs = c(2.5/100, 97.5/100))

paste("race")
sim.race.num <- lapply(nsim.vec, function (x) summary(sim_results[[x]] ~ nodemix("race.num")))
#quantiles
mean(unlist(lapply(sim.race.num, function (x) x["mix.race.num.1.1"])))
quantile(unlist(lapply(sim.race.num, function (x) x["mix.race.num.1.1"])), probs = c(2.5/100, 97.5/100))
mean(unlist(lapply(sim.race.num, function (x) x["mix.race.num.2.1"])))
quantile(unlist(lapply(sim.race.num, function (x) x["mix.race.num.2.1"])), probs = c(2.5/100, 97.5/100))
mean(unlist(lapply(sim.race.num, function (x) x["mix.race.num.3.1"])))
quantile(unlist(lapply(sim.race.num, function (x) x["mix.race.num.3.1"])), probs = c(2.5/100, 97.5/100))
mean(unlist(lapply(sim.race.num, function (x) x["mix.race.num.4.1"])))
quantile(unlist(lapply(sim.race.num, function (x) x["mix.race.num.4.1"])), probs = c(2.5/100, 97.5/100))
mean(unlist(lapply(sim.race.num, function (x) x["mix.race.num.1.2"])))
quantile(unlist(lapply(sim.race.num, function (x) x["mix.race.num.1.2"])), probs = c(2.5/100, 97.5/100))
mean(unlist(lapply(sim.race.num, function (x) x["mix.race.num.2.2"])))
quantile(unlist(lapply(sim.race.num, function (x) x["mix.race.num.2.2"])), probs = c(2.5/100, 97.5/100))
mean(unlist(lapply(sim.race.num, function (x) x["mix.race.num.3.2"])))
quantile(unlist(lapply(sim.race.num, function (x) x["mix.race.num.3.2"])), probs = c(2.5/100, 97.5/100))
mean(unlist(lapply(sim.race.num, function (x) x["mix.race.num.4.2"])))
quantile(unlist(lapply(sim.race.num, function (x) x["mix.race.num.4.2"])), probs = c(2.5/100, 97.5/100))
mean(unlist(lapply(sim.race.num, function (x) x["mix.race.num.1.3"])))
quantile(unlist(lapply(sim.race.num, function (x) x["mix.race.num.1.3"])), probs = c(2.5/100, 97.5/100))
mean(unlist(lapply(sim.race.num, function (x) x["mix.race.num.2.3"])))
quantile(unlist(lapply(sim.race.num, function (x) x["mix.race.num.2.3"])), probs = c(2.5/100, 97.5/100))
mean(unlist(lapply(sim.race.num, function (x) x["mix.race.num.3.3"])))
quantile(unlist(lapply(sim.race.num, function (x) x["mix.race.num.3.3"])), probs = c(2.5/100, 97.5/100))
mean(unlist(lapply(sim.race.num, function (x) x["mix.race.num.4.3"])))
quantile(unlist(lapply(sim.race.num, function (x) x["mix.race.num.4.3"])), probs = c(2.5/100, 97.5/100))
mean(unlist(lapply(sim.race.num, function (x) x["mix.race.num.1.4"])))
quantile(unlist(lapply(sim.race.num, function (x) x["mix.race.num.1.4"])), probs = c(2.5/100, 97.5/100))
mean(unlist(lapply(sim.race.num, function (x) x["mix.race.num.2.4"])))
quantile(unlist(lapply(sim.race.num, function (x) x["mix.race.num.2.4"])), probs = c(2.5/100, 97.5/100))
mean(unlist(lapply(sim.race.num, function (x) x["mix.race.num.3.4"])))
quantile(unlist(lapply(sim.race.num, function (x) x["mix.race.num.3.4"])), probs = c(2.5/100, 97.5/100))
mean(unlist(lapply(sim.race.num, function (x) x["mix.race.num.4.4"])))
quantile(unlist(lapply(sim.race.num, function (x) x["mix.race.num.4.4"])), probs = c(2.5/100, 97.5/100))

paste("gender")
sim.gender <- lapply(nsim.vec, function (x) summary(sim_results[[x]] ~ nodemix("gender")))
#quantile
mean(unlist(lapply(sim.gender, function (x) x["mix.gender.female.female"])))
quantile(unlist(lapply(sim.gender, function (x) x["mix.gender.female.female"])), probs = c(2.5/100, 97.5/100))
mean(unlist(lapply(sim.gender, function (x) x["mix.gender.male.female"])))
quantile(unlist(lapply(sim.gender, function (x) x["mix.gender.male.female"])), probs = c(2.5/100, 97.5/100))
mean(unlist(lapply(sim.gender, function (x) x["mix.gender.female.male"])))
quantile(unlist(lapply(sim.gender, function (x) x["mix.gender.female.male"])), probs = c(2.5/100, 97.5/100))
mean(unlist(lapply(sim.gender, function (x) x["mix.gender.male.male"])))
quantile(unlist(lapply(sim.gender, function (x) x["mix.gender.male.male"])), probs = c(2.5/100, 97.5/100))

paste("age")
sim.young <- lapply(nsim.vec, function (x) summary(sim_results[[x]] ~ nodemix("young")))
#quantiles
mean(unlist(lapply(sim.young, function (x) x["mix.young.0.0"])))
quantile(unlist(lapply(sim.young, function (x) x["mix.young.0.0"])), probs = c(2.5/100, 97.5/100))
mean(unlist(lapply(sim.young, function (x) x["mix.young.1.0"])))
quantile(unlist(lapply(sim.young, function (x) x["mix.young.1.0"])), probs = c(2.5/100, 97.5/100))
mean(unlist(lapply(sim.young, function (x) x["mix.young.0.1"])))
quantile(unlist(lapply(sim.young, function (x) x["mix.young.0.1"])), probs = c(2.5/100, 97.5/100))
mean(unlist(lapply(sim.young, function (x) x["mix.young.1.1"])))
quantile(unlist(lapply(sim.young, function (x) x["mix.young.1.1"])), probs = c(2.5/100, 97.5/100))


paste("dist")
sim.dist <- lapply(nsim.vec, function (x) summary(sim_results[[x]] ~ dist(1:4)))
#quantiles
mean(unlist(lapply(sim.dist, function (x) x["dist1"])))
quantile((unlist(lapply(sim.dist, function (x) x["dist1"]))), probs = c(2.5/100, 97.5/100))
mean(unlist(lapply(sim.dist, function (x) x["dist2"])))
quantile((unlist(lapply(sim.dist, function (x) x["dist2"]))), probs = c(2.5/100, 97.5/100))
mean(unlist(lapply(sim.dist, function (x) x["dist3"])))
quantile((unlist(lapply(sim.dist, function (x) x["dist3"]))), probs = c(2.5/100, 97.5/100))
mean(unlist(lapply(sim.dist, function (x) x["dist4"])))
quantile((unlist(lapply(sim.dist, function (x) x["dist4"]))), probs = c(2.5/100, 97.5/100))